# Generated by Django 5.0.3 on 2024-03-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ParcelLocker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("locker_number", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=255)),
                ("street", models.CharField(max_length=100)),
                ("street_number", models.CharField(max_length=20)),
                ("capacity", models.IntegerField(default=0)),
            ],
        ),
    ]
