# Generated by Django 5.0.3 on 2024-03-18 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_user_password"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
